export const leads = [
    {
      id: 1,
      name: "Shoraximov Shamsiddin",
      phone: "99 811 11 11",
      from: "Telegram",
      section: "Elementary",
      avatar: "E",
    },
    {
      id: 2,
      name: "Asliddinov Odilbek",
      phone: "99 811 11 11",
      from: "Instagram",
      section: "Pre - Inter",
      avatar: "https://source.unsplash.com/random/40x40",
    },
    {
      id: 3,
      name: "Ravshanjon",
      phone: "99 811 11 11",
      from: "Xolasi orqali",
      section: "Beginer",
      avatar: "W",
    },
    {
      id: 4,
      name: "Ulug’bek",
      phone: "99 811 11 11",
      from: "---",
      section: "Pre - Inter",
      avatar: "S",
    },
    {
      id: 5,
      name: "Sattor",
      phone: "99 811 11 11",
      from: "---",
      section: "Elementary",
      avatar: "D",
    },
    {
      id: 6,
      name: "Eshonbek",
      phone: "99 811 11 11",
      from: "---",
      section: "Beginer",
      avatar: "E",
    },
  ];